### ISSUE TITLE
Caught exception: TypeError: Cannot call method 'error' of undefined

### ISSUE THREAD

**Issue by drazisil** [drazisil/dashboard-zero#60]
````
Trace
    at processIssueComments (/home/drazisil/dev/dashboard-zero/src/dashboard-zero/github.js:416:15)
    at cb_get_comments_from_issue (/home/drazisil/dev/dashboard-zero/src/dashboard-zero/github.js:392:30)
    at Object.proto.sendError (/home/drazisil/dev/dashboard-zero/node_modules/github/api/v3.0.0/index.js:32:13)
    at /home/drazisil/dev/dashboard-zero/node_modules/github/api/v3.0.0/issues.js:351:29
    at callCallback (/home/drazisil/dev/dashboard-zero/node_modules/github/index.js:743:17)
    at ClientRequest.<anonymous> (/home/drazisil/dev/dashboard-zero/node_modules/github/index.js:815:17)
    at ClientRequest.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1797:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
Caught exception: TypeError: Cannot call method 'error' of undefined
Trace
    at process.module.exports.error (/home/drazisil/dev/dashboard-zero/src/dashboard-zero/logger.js:5:11)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
````

**Comment by drazisil** [comment]
This is good now, using verror for better error handling
